version: "3.7"

services:
  db:
    image: pre-atividade-db:latest
    container_name: pre-atividade-db
    networks:
      - atividade2
    ports:
      - "25432:5432"
    environment:
      POSTGRES_DB: notes
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: 123456
      PGDATA: /var/lib/postgresql/data/atividade-db
    volumes:
      - atividade-db:/var/lib/postgresql/data
  
  api:
    image: pre-atividade-api:latest
    container_name: pre-atividade-api
    networks:
      - atividade2
    ports:
      - '5000:5000'
    restart: unless-stopped
    tty: true

volumes:
  atividade-db:

networks:
  atividade2:
    driver: "bridge"